python3 ~/johnkim/tools/deeplearning/estimator/SemanticClassifier.py \
	--train \
	-d \
	-i lv_train_imgs \
	-t lv_train_masks \
	-o trained_model/ \
	--loss CrossEntropy \
	-model UNet2d \
		--dropout_rate 0.15 \
		--num_output_channels 2 \
	--data_cache_limit 32 \
	--patch_size 64 64 7 \
	--target_patch_size 64 64 1 \
	--target_patch_offset 0 0 3 \
	--num_epochs 100 \
	--epoch_size 5120 \
	--batch_size 128 \
	--data_normalization quantile \
	--pad_size 0 0 3 \
	--augment \
		--flip 0 \
